// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_FTPDEMO_FTPDEMO_H
#define ANALYZER_PROTOCOL_FTPDEMO_FTPDEMO_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "ftpdemo_pac.h"

namespace analyzer { namespace FTPDemo {

class FTPDEMO_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	FTPDEMO_Analyzer(Connection* conn);
	virtual ~FTPDEMO_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);
	

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new FTPDEMO_Analyzer(conn); }

protected:
	binpac::FTPDEMO::FTPDEMO_Conn* interp;
	
	bool had_gap;
	
};

} } // namespace analyzer::* 

#endif