// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "FTPDEMO.h"

namespace plugin {
namespace Bro_FTPDEMO {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("FTPDEMO",
		             ::analyzer::FTPDemo::FTPDEMO_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::FTPDEMO";
		config.description = "File Transmission Protocol analyzer";
		return config;
		}
} plugin;

}
}